name: clienteapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3
  google_maps_flutter: ^2.0.1
  google_maps_webservice: ^0.0.19
  json_serializable: ^4.1.0
  provider: ^5.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.10.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ajustes-01.png
    - assets/amigos.png
    - assets/avion-de-papel-01.png
    - assets/ayudar-01.png
    - assets/bandera-01.png
    - assets/bloquear-01.png
    - assets/bolsa-de-descuento-01.png
    - assets/calendario-01.png
    - assets/calendario-dia-01.png
    - assets/car-01.png
    - assets/cargando-01.png
    - assets/carril-01.png
    - assets/casa-01.png
    - assets/charla-01.png
    - assets/compartir-icono-01.png
    - assets/corazon-01.png
    - assets/dibujar-01.png
    - assets/enlace-roto-01.png
    - assets/espana-01.png
    - assets/esperando-01.png
    - assets/favorite-01.png
    - assets/grupo-de-usuario-01.png
    - assets/guardar-01.png
    - assets/hoja-01.png
    - assets/hora-01.png
    - assets/lapiz-01.png
    - assets/licencia-de-conducir-01.png
    - assets/location-01.png
    - assets/mano-01.png
    - assets/menu-01.png
    - assets/metodo-pago-01.png
    - assets/mi-ubi-01.png
    - assets/pago-en-efectivo-01.png
    - assets/parada-01.png
    - assets/premium-01.png
    - assets/red-elementos-01.png
    - assets/regalo-01.png
    - assets/reloj-01.png
    - assets/salir.png
    - assets/silla-de-ruedas-01.png
    - assets/tarjeta-de-credito-01.png
    - assets/taxi-01.png
    - assets/taximetro-01.png
    - assets/telefono-01.png
    - assets/tick-01.png
    - assets/trabajo-01.png
    - assets/user-01.png
    - assets/usuario-01.png
    - assets/volante-01.png
    - assets/Andrea.jpg
    - assets/Gustavo.jpg
    - assets/Paco.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText-Bold
      fonts:
       - asset: assets/SFProText-Bold.ttf
    - family: SFProText-Semibold
      fonts:
       - asset: assets/SFProText-Semibold.ttf
    - family: SFProText-Regular
      fonts:
       - asset: assets/SFProText-Regular.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
